### ISSUE TITLE
Caused by java.nio.channels.ClosedChannelException

### ISSUE THREAD

**Issue by ArthurSav** [dizitart/nitrite-database#80] opened 2018-06-13 09:25 UTC
I have some background operations and async tasks that seem to cause an exception.

```
java.nio.FileChannelImpl.read (FileChannelImpl.java:283)
arrow_right
org.h2.store.fs.FileNio.read (FilePathNio.java:74)
org.h2.mvstore.DataUtils.readFully (DataUtils.java:421)
org.h2.mvstore.FileStore.readFully (FileStore.java:98)
org.h2.mvstore.Page.read (Page.java:190)
org.h2.mvstore.MVStore.readPage (MVStore.java:1952)
org.h2.mvstore.MVMap.readPage (MVMap.java:741)
org.h2.mvstore.Page.getChildPage (Page.java:217)
org.h2.mvstore.MVMap.binarySearch (MVMap.java:473)
org.h2.mvstore.MVMap.get (MVMap.java:455)
org.dizitart.no2.store.NitriteMVMap.get (NitriteMVMap.java:51)
org.dizitart.no2.store.NitriteMVMap.updateAttributes (NitriteMVMap.java:170)
org.dizitart.no2.store.NitriteMVMap.put (NitriteMVMap.java:88)
org.dizitart.no2.internals.DataService.update (DataService.java:181)
org.dizitart.no2.internals.NitriteService.update (NitriteService.java:361)
org.dizitart.no2.internals.DefaultNitriteCollection.update (DefaultNitriteCollection.java:322)
org.dizitart.no2.objects.DefaultObjectRepository.update (DefaultObjectRepository.java:141)
org.dizitart.no2.objects.DefaultObjectRepository.update (DefaultObjectRepository.java:126) ...
```

Since it's android, i guess it happens when a background tasks is running and the app closes.
Any more insight about the when this exception can occur?

**Comment by anidotnet** [comment] 2018-06-13 09:38
I guess you are not using the latest snapshot - 3.0.1-SNAPSHOT. The line number in stacktrace does not map with the code. I have added proper synchronization for update. You can try that one. But if the issue is still not resolved, you need to keep the background process running and not close the app. Most probably your assumptions is right.

**Comment by ArthurSav** [comment] 2018-06-14 14:19
> you need to keep the background process running and not close the app
Unfortunately that is not possible.

Have updated to 3.0.1 and added a check to see of the db is open before attempting to insert/update.
It should do the trick but i'll find out in a few days for sure.

**Comment by anidotnet** [comment] 2018-06-14 15:54
Thanks for the update. I'll keep this issue opened. If you don’t see any problem let me know so that I can close this issue.

**Closed** 2018-06-28 05:29 UTC

**Comment by ArthurSav** [comment] 2018-07-16 09:13
FYI, this is still an issue and it happens very frequently (both during background and non background operations).


org.h2.mvstore.DataUtils.newIllegalStateException (DataUtils.java:765)
--
  | org.h2.mvstore.DataUtils.readFully (DataUtils.java:435)
  | org.h2.mvstore.FileStore.readFully (FileStore.java:98)
  | org.h2.mvstore.Page.read (Page.java:190)
  | org.h2.mvstore.MVStore.readPage (MVStore.java:1952)
  | org.h2.mvstore.MVMap.readPage (MVMap.java:741)
  | org.h2.mvstore.MVMap.setRootPos (MVMap.java:751)
  | org.h2.mvstore.MVStore.openMap (MVStore.java:476)
  | org.h2.mvstore.MVStore.openMap (MVStore.java:427)
  | org.dizitart.no2.store.NitriteMVStore.openMap (NitriteMVStore.java:89)
  | org.dizitart.no2.internals.IndexMetaService.getIndexMetadata (IndexMetaService.java:152)
  | org.dizitart.no2.internals.IndexMetaService.hasIndex (IndexMetaService.java:60)
  | org.dizitart.no2.internals.NitriteService.hasIndex (NitriteService.java:90)
  | org.dizitart.no2.internals.DefaultNitriteCollection.hasIndex (DefaultNitriteCollection.java:114)
  | org.dizitart.no2.objects.DefaultObjectRepository.createIndexes (DefaultObjectRepository.java:314)
  | org.dizitart.no2.objects.DefaultObjectRepository.initRepository (DefaultObjectRepository.java:300)
  | org.dizitart.no2.objects.DefaultObjectRepository.<init> (DefaultObjectRepository.java:57)
  | org.dizitart.no2.objects.RepositoryFactory.open (RepositoryFactory.java:46)
  | org.dizitart.no2.Nitrite.getRepository (Nitrite.java:139)
  | storage.Database.getStatsRepo (Database.java:426)
  | storage.Database.getStats (Database.java:282)
  | stats.StatsFragment.onCreateView (StatsFragment.java:58)




sun.nio.ch.FileChannelImpl.ensureOpen (FileChannelImpl.java:109)
--
  | sun.nio.ch.FileChannelImpl.read (FileChannelImpl.java:700)
  | org.h2.store.fs.FileNio.read (FilePathNio.java:74)
  | org.h2.mvstore.DataUtils.readFully (DataUtils.java:421)
  | org.h2.mvstore.FileStore.readFully (FileStore.java:98)
  | org.h2.mvstore.Page.read (Page.java:190)
  | org.h2.mvstore.MVStore.readPage (MVStore.java:1952)
  | org.h2.mvstore.MVMap.readPage (MVMap.java:741)
  | org.h2.mvstore.MVMap.setRootPos (MVMap.java:751)
  | org.h2.mvstore.MVStore.openMap (MVStore.java:476)
  | org.h2.mvstore.MVStore.openMap (MVStore.java:427)
  | org.dizitart.no2.store.NitriteMVStore.openMap (NitriteMVStore.java:89)
  | org.dizitart.no2.internals.IndexMetaService.getIndexMetadata (IndexMetaService.java:152)
  | org.dizitart.no2.internals.IndexMetaService.hasIndex (IndexMetaService.java:60)
  | org.dizitart.no2.internals.NitriteService.hasIndex (NitriteService.java:90)
  | org.dizitart.no2.internals.DefaultNitriteCollection.hasIndex (DefaultNitriteCollection.java:114)
  | org.dizitart.no2.objects.DefaultObjectRepository.createIndexes (DefaultObjectRepository.java:314)
  | org.dizitart.no2.objects.DefaultObjectRepository.initRepository (DefaultObjectRepository.java:300)
  | org.dizitart.no2.objects.DefaultObjectRepository.<init> (DefaultObjectRepository.java:57)
  | org.dizitart.no2.objects.RepositoryFactory.open (RepositoryFactory.java:46)
  | org.dizitart.no2.Nitrite.getRepository (Nitrite.java:139)
  | storage.Database.getStatsRepo (Database.java:426)
  | storage.Database.getStats (Database.java:282)
  | stats.StatsFragment.onCreateView (StatsFragment.java:58)
  | android.support.v4.app.Fragment.performCreateView (Fragment.java:2346)

**Comment by anidotnet** [comment] 2018-07-16 09:53
It would be very helpful if you somehow provide me some reproducible code. From your stacktrace it is clear that database file has been closed while making a `openMap()` call. My suggestion is you should always call nitrite's `openOrCreate()` in your activity's `onCreate()`. So that it will ensure whenever an activity get destroyed and re-created you will open a new nitrite instance.

Secondly, by default nitrite registers a shutdown hook which auto-closes the file system. In your nitrite builder call `disableShutdownHook()` to disable the auto-close feature. It has been introduced in the latest snapshot.

**Comment by ArthurSav** [comment] 2018-07-16 12:47
It's a bit hard to share reproducible code for a non open source app. Even more i can't reproduce it myself - it's just that i see a lot of crashes from my users.

I would say the usage is pretty standard.

i.e As you can see from the stacktrace the app crashes when a fragment is opened during onCreateView
The db query is pretty simple as well 

```
public List<Stats> getStats(Long userId) {
    ObjectFilter withUserId = ObjectFilters.eq("userId", userId);
    FindOptions orderByDate = FindOptions.sort("date", SortOrder.Descending);
    return getStatsRepository().find(withUserId, orderByDate).toList();
  }
```

>My suggestion is you should always call nitrite's openOrCreate()

How costly is that in performance/memory terms?

> whenever an activity get destroyed and re-created you will open a new nitrite instance

Shouldn't this `nitrite == null || nitrite.isClosed()` be enough? Shouldn't `isClosed` return true in that case?

> disableShutdownHook()

If i use this method, do i have to close the db manually?
