### ISSUE TITLE
too slow on Android

### ISSUE THREAD

**Issue by FunnyDevs** [dizitart/nitrite-database#18] opened 2017-06-30 08:54 UTC
I tried it on Android and is slower than sqlite. Any improvements?

**Comment by anidotnet** [comment] 2017-06-30 09:02
For which operations do you see performance degradation? Do you have the benchmark code to share? May be I can look into it and suggest something. A vague remarks like this is not much helpful for me.

**Comment by FunnyDevs** [comment] 2017-06-30 10:28
i make a test with these POJOs

```
public class PrivateConversation
{
    private String objectId;
    private User user1;
    private User user2;
    private Integer total;
    private String lastMessage;

   //...gettes and setters
}
```

```
public class User
{

    private String objectId;
    private String about;
    private String name;
    private String image;
    private Boolean isSocial;
    private String password;
    private String location;

}
```

```
public class PrivateMessage extends BaseModel
{
    private String objectId;
    private User sender;
    private String text;
    private User recipient;
    private PrivateConversation privateConversation;
}
```

I saved 28 PrivateMessage. When i do a find operation, it takes 200-300ms, in sqlite 60-100 ms

**Comment by anidotnet** [comment] 2017-06-30 10:42
Can you please also provide the code you have written for - creating the database, inserting the data and find operation? Have you created any index and using it for find operation?

One thing you need to remember, when you use objects, the json serialization overhead is there. If you need improvement, you can use the ```NitriteCollection``` instead of ```ObjectRepository```. In case of ```NitriteCollection``` there is no serialization overhead involved. 

If you have enabled compression or compaction while creating the database, it may slow down the write operations. If you share the full code, I can give you better insight.

**Comment by FunnyDevs** [comment] 2017-06-30 10:49
Creating database

```
db = Nitrite.builder()
                .filePath(getFilesDir()+"/test.db")
                .openOrCreate();
```

Insert Data
`privateMessageObjectRepository.insert(privateMessageList.toArray(new PrivateMessage[0]));`

find data (i have created no index because the database is popolated with only 28 values)
`privateMessageList = privateMessageObjectRepository.find().toList();`

**Comment by anidotnet** [comment] 2017-06-30 11:28
Your code looks alright at a glance. It seems the json serialization overhead is making all the differences. Can you try with ```NitriteCollection``` by using ```Document``` directly instead of objects to check if you gain anything or not?

While using objects, I cannot bypass the serialization overhead. Anyway, the concerned logic is there in this file [ObjectCursor](https://github.com/dizitart/nitrite-database/blob/master/nitrite/src/main/java/org/dizitart/no2/objects/ObjectCursor.java), may be you can  have a look and suggest something to improve it.

**Comment by FunnyDevs** [comment] 2017-06-30 12:07
I try with Document, mapping only Document<--> PrivateMessage and it's very fast, it takes 10-20 ms. The Json mapping of "PrivateMessage" class is the bottleneck. Maybe using another mapping tecnique like KryoSerialization or MessagePack could improve the serialization.
Inside the fetched Documents every reference of other object (User and PrivateConversation) is resolved very fast.

**Comment by anidotnet** [comment] 2017-06-30 13:12
I'll take a look at those libraries, but also I need to verify if they have the same customization capabilities like jackson or not. Meantime you can attach your own serialization library also here and bypass jackson. All you need to do is implement [```NitriteMapper```](https://github.com/dizitart/nitrite-database/blob/master/nitrite/src/main/java/org/dizitart/no2/internals/NitriteMapper.java) interface using your serialization library and set it while creating the database.

```java
db = Nitrite.builder()
                .filePath(getFilesDir()+"/test.db")
                .nitriteMapper(myCustomMapper)
                .openOrCreate();
```

You can have look at this class as an example [```JacksonMapper```](https://github.com/dizitart/nitrite-database/blob/master/nitrite/src/main/java/org/dizitart/no2/internals/JacksonMapper.java). If you see performance improvement you can contribute the code here also. I'll be more than happy to accept the PR.

**Comment by anidotnet** [comment] 2017-06-30 13:50
I just had a quick look at both Kryo and MessagePack, but what I understood is they are not json serialization libraries. Kryo does more of a binary serialization and MessagePack generates an encoded version of json, both of them are not suitable in this use case. The reason is, we need a serializer which can creates a key-value map from an object which will be used to convert an object instance to a ```Document```, which jackson does flawlessly. Please correct me if I have missed something.

**Comment by FunnyDevs** [comment] 2017-06-30 14:03
No,they are not json serialization libraries. There are other json libraries faster than jackson (like LoganSquare) but they require a pojo annotation process...

**Comment by anidotnet** [comment] 2017-06-30 14:35
Annotation processing is also not favorable in this use case, user needs to have complete control over the pojo.

**Comment by anidotnet** [comment] 2017-07-06 07:48
I validated Boon with Jackson. They seem to have the same response time for map to object conversion for a simple class. Moreover, boon does not seems to have any functionality to handle circular reference. So jackson is better suited here than boon.

Need to validate LoganSquare also. What I think is to speed up the process, I can introduce assisted serialization much like Externalizable technique in java. That way I can somewhat bypass the reflection overhead. Let me know what is your opinion.

**Comment by FunnyDevs** [comment] 2017-07-06 10:47
Yes, i think it's the best approach. Reflection is a performance bottleneck in Android if used for a long number of classes. In fact even Jackson have a module to bypass reflection (Jackson Afterburner Module)

**Comment by anidotnet** [comment] 2017-07-08 07:47
I have committed the changes in master. All you need to do is to implement your POJO classes from `Mappable` interface. One example can be found here [User.java](https://github.com/dizitart/nitrite-database/blob/master/example-android-app/src/main/java/org/dizitart/no2/sample/android/User.java). 

But remember, artifact is not published to maven yet, so you have to build it from master. Let me know if that fulfil your performance requirement or not.

**Comment by FunnyDevs** [comment] 2017-07-09 20:17
ok,within next week-end i'll try these new changes!

**Comment by FunnyDevs** [comment] 2017-07-11 21:40
I'm trying your changes inside my complex logic (i have used document to avoid jackson databind), but now i have always problem with "NO2.2004: store is closed " on NitriteCollection after used ObjectRepository.

**Comment by anidotnet** [comment] 2017-07-12 01:50
If possible can you please provide the relevant code section and error stack trace? There is a very little info here. The store closed error only comes if the store is closed by the user prior calling any operation on NitriteCollection.

And to avoid databind, you don't need to use Document now directly. You can use object and ObjectRepository, but your object must implement ```Mappable``` interface.

And can you clarify what did you mean by that?

> on NitriteCollection after used ObjectRepository.

**Comment by pguli** [comment] 2017-07-12 05:45
I had mapped the entire applicativo with documents to avoid databind. Now, to try your changes, i have created a local branch of my app and changed only a section to test objectrepository ( instead change entire project) but i have this kind of problem. It Is even difficult give you a specific snippet of code. I think only that document and objectrepository together have problems. So the only solution Is trying to remap new branch with only objectrepository(2-3 hours of work)

**Comment by FunnyDevs** [comment] 2017-07-12 05:47
I have mapped the entire applicativo with documents to avoid databind. Now, to try your changes, i have created a local branch of my app and changed only a section to test objectrepository ( instead change entire project) but i have this kind of problem. It Is even difficult give you a specific snippet of code. I think only that document and objectrepository together have problems. So the only solution Is trying to remap new branch with only objectrepository(2-3 hours of work)

**Comment by anidotnet** [comment] 2017-07-12 06:44
Yes, if you use ObjectRepository, don't use Document, use objects. If you use NItriteCollection use only Document. But after my recent changes, you can discard your Document related changes and use ObjectRepository only. Just remember to implement ```Mappable``` for your POJOs.

**Comment by FunnyDevs** [comment] 2017-07-13 20:31
i found that the store closes because throw this exception:

 Caused by: java.lang.IllegalStateException: Last block not stored, possibly due to out-of-memory [1.4.196/3]

**Comment by anidotnet** [comment] 2017-07-14 01:28
As the error says somehow your code hits out of memory error in Mvstore library. 
On another note, just curious if you are still mixing ObjectRepository with documents or are you using objects only?

**Comment by FunnyDevs** [comment] 2017-07-14 05:36
No, i have refactored with only objectrepository.

**Comment by anidotnet** [comment] 2017-07-14 05:51
Then you have to look into your code to see how an out-of-memory error is occurring. Start with some simple ObjectRepository operations to verify the performance improvement. Then add your code complexity on top of it one by one to identify the root cause of the error. There is very little information I have to help you.

**Comment by FunnyDevs** [comment] 2017-07-14 06:01
The error occurs in a find operation. The Memory error, in my opinion, throws because i have a mappale object with inside other mappable objects

**Comment by anidotnet** [comment] 2017-07-14 06:23
I just wrote a quick test with nested mappable objects (```MappableEmployee``` inside ```MappableDepartment```) but it runs fine. I think you need to pay attention to the conversion logic you have written to check if you have accidentally introduced any endless recursion. You can take help from below example.

```java

@Data
@ToString
public class MappableEmployee implements Mappable {
    private String empId;
    private String name;
    private Date joiningDate;
    private MappableEmployee boss;

    @Override
    public Document write(NitriteMapper mapper) {
        Document document = new Document();
        document.put("empId", getEmpId());
        document.put("name", getName());
        document.put("joiningDate", getJoiningDate());

        if (getBoss() != null) {
            Document bossDoc = getBoss().write(mapper);
            document.put("boss", bossDoc);
        }
        return document;
    }

    @Override
    public void read(NitriteMapper mapper, Document document) {
        if (document != null) {
            setEmpId((String) document.get("empId"));
            setName((String) document.get("name"));
            setJoiningDate((Date) document.get("joiningDate"));

            Document bossDoc = (Document) document.get("boss");
            if (bossDoc != null) {
                MappableEmployee bossEmp = new MappableEmployee();
                bossEmp.read(mapper, bossDoc);
                setBoss(bossEmp);
            }
        }
    }
}


@Data
@ToString
public class MappableDepartment implements Mappable {
    private String name;
    private List<MappableEmployee> employeeList = new ArrayList<>();

    @Override
    public Document write(NitriteMapper mapper) {
        Document document = new Document();

        document.put("name", getName());
        List<Document> employees = new ArrayList<>();
        for (MappableEmployee employee: getEmployeeList()) {
            employees.add(employee.write(mapper));
        }
        document.put("employeeList", employees);

        return document;
    }

    @Override
    @SuppressWarnings("unchecked")
    public void read(NitriteMapper mapper, Document document) {
        if (document != null) {
            setName((String) document.get("name"));
            for (Document doc : (List<Document>) document.get("employeeList")) {
                MappableEmployee me = new MappableEmployee();
                me.read(mapper, doc);
                getEmployeeList().add(me);
            }
        }
    }
}


public class MapperTest {
    private JacksonMapper jacksonMapper;

    @Before
    public void setUp() {
        jacksonMapper = new JacksonMapper();
    }

    @Test
    public void testNested() {
        final MappableEmployee boss = new MappableEmployee();
        boss.setEmpId("1");
        boss.setName("Boss");
        boss.setJoiningDate(new Date());

        final MappableEmployee emp1 = new MappableEmployee();
        emp1.setEmpId("abcd");
        emp1.setName("Emp1");
        emp1.setJoiningDate(new Date());
        emp1.setBoss(boss);

        MappableDepartment department = new MappableDepartment();
        department.setName("Dept");
        department.setEmployeeList(new ArrayList<MappableEmployee>() {{ add(boss); add(emp1); }});

        long start = System.currentTimeMillis();
        Document document = jacksonMapper.asDocument(department);
        long diff = System.currentTimeMillis() - start;
        System.out.println(diff);

        start = System.currentTimeMillis();
        MappableDepartment dept = jacksonMapper.asObject(document, MappableDepartment.class);
        diff = System.currentTimeMillis() - start;
        System.out.println(diff);
        assertEquals(department, dept);
    }

}

**Comment by FunnyDevs** [comment] 2017-07-14 17:52
Is possibile to use "db.getRepository" for the same class twice? Because i have to navigate between activities and the exception occurs when i call the find in second Activity

**Comment by anidotnet** [comment] 2017-07-14 18:21
Yes you can call getRepository multiple times. But you need to remember few things

1. Multiple getRepository call for a particular type open the same underlying MVMap
2. But each getRepository call will give you new instances of ObjectRepository each time, though all of them will point to the same MVMap

So if you inadvertently close one instance, all other instances will also get closed instantly as the underlying MVMap is same, hence you will get a store closed error if you try to access one instance afterwards.

For an idiomatic usage of getRepository() please have a look at the [sample android activity](https://github.com/dizitart/nitrite-database/blob/master/example-android-app/src/main/java/org/dizitart/no2/sample/android/MainActivity.java)

**Comment by anidotnet** [comment] 2017-07-14 18:33
If you still could not pin-point the cause, please provide me with a reproducible code to debug.

**Comment by anidotnet** [comment] 2017-07-27 14:08
Closing this issue for inactivity. If you still facing any issue feel free to open it.

**Closed by anidotnet** 2017-07-27 14:08 UTC
Labels: enhancement
