### ISSUE TITLE
find(...): NoSuchElementException for existed object

### ISSUE THREAD

**Issue by Try4W** [dizitart/nitrite-database#58] opened 2018-02-21 10:33 UTC
Hi again! ;)

Sometimes when I trying to find an object like this:
```
    fun get(localId: UUID) = Single.fromCallable {
        repository.find(
                ObjectFilters.eq(CaObject::localId.name, localId)
        ).first()
    }
```

I get `java.util.NoSuchElementException: Collection is empty.` exception while object with such `id` exists and the rest of the time successfully queried.

```
	Caused by: java.util.NoSuchElementException: Collection is empty.
	   at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:166)
	   at eu.cortex.cortexalarm.data.daos.caobjects.CaObjectsDao$get$1.call(CaObjectsDao.kt:46)
	   at eu.cortex.cortexalarm.data.daos.caobjects.CaObjectsDao$get$1.call(CaObjectsDao.kt:17)
	   at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
```

It happens sometimes when I trying to find object just after upserting with the same `id` on the last SNAPSHOT and 2.1.1.

**Comment by anidotnet** [comment] 2018-02-21 12:59
Would you help me reproduce this issue? I have this test code, but could not reproduce it for single time

```kotlin
	@Test
    fun testIssue58() {
        val repository = db?.getRepository<CaObject>()!!
        val uuid = UUID.randomUUID()
        repository.insert(CaObject(uuid, "1234"))

        fun get(localId: UUID) = Single.fromCallable {
            repository.find(
                    ObjectFilters.eq(CaObject::localId.name, localId)
            ).first()
        }

        assertNotNull(get(uuid).blockingGet())
    }
```

**Comment by Try4W** [comment] 2018-02-23 08:16
Done!

```
class DbTests {

    private val objectMapper = ObjectMapper()

    private val db = nitrite {}

    @Test
    fun testIssue58() {
        val repository = db.getRepository(SimpleObject::class.java)
        val executor = Executors.newFixedThreadPool(10)

        val uuid = UUID.randomUUID()
        val latch = CountDownLatch(100)

        repository.update(SimpleObject(
                uuid,
                true
        ), true)

        for(i in 0..100) {
            executor.submit {
                val simpleObject = repository.find(
                        ObjectFilters.eq(SimpleObject::id.name, uuid)
                ).first()

                repository.update(simpleObject.copy(
                        value = !simpleObject.value
                ))

                executor.submit {
                    val result = repository.find(
                            ObjectFilters.eq(SimpleObject::id.name, uuid)
                    )
                    latch.countDown()
                    System.out.println("left ${latch.count}, found ${result.totalCount()}")
                }
            }
        }
        latch.await()
    }

    data class SimpleObject(
            @Id val id: UUID,
            val value: Boolean
    )

}
```

Sometimes this code prints:
```
left 57, found 1
left 59, found 0
```

**Comment by anidotnet** [comment] 2018-02-23 08:49
I'll look into it.

**Comment by anidotnet** [comment] 2018-02-24 07:59
Nice catch. It was happening due to a race condition while updating the index entries. It should be fixed now.

**Closed by anidotnet** 2018-02-24 07:59 UTC
Labels: bug
