### ISSUE TITLE
DB file is being overwritten everytime I run the App

### ISSUE THREAD

**Issue by Vijeta141** [dizitart/nitrite-database#150] opened 2019-04-09 07:22 UTC
Whenever i run my app, the db file is overwritten and all past data is erased. The documents added earlier cannot be found.
```java
public class MainActivity extends AppCompatActivity {

    private Nitrite db;
    //private ObjectRepository<Rules> repository;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);


        if (db == null) {

            String fileName = getFilesDir().getPath() + "/test.db";
            Log.i("Nitrite", "Nitrite file - " + fileName);
            db = Nitrite.builder()
                    .filePath(fileName)
                    .openOrCreate("test-user", "test-password");

            NitriteCollection collection = db.getCollection("Rules");
            Document doc = Document.createDocument("firstName", "#12345")
                    .put("lastName", "Doe")
                    .put("birthDay", new Date())
                    .put("data", new byte[] {1, 2, 3})
                    .put("fruits", new ArrayList<String>() {{ add("apple"); add("orange"); add("banana"); }})
                    .put("note", "a quick brown fox jump over the lazy dog");
            collection.insert(doc);

            Exporter exporter = Exporter.of(db);
            String fileName1 = getFilesDir().getPath() + "/Rules.json";
            exporter.exportTo(fileName1);


        }
    }

```

The exported file is not adding the document again as it should be after running again.
Could you please let me know what could be causing this?

**Comment by Vijeta141** [comment] 2019-04-09 07:38
Also, if i try to run db.close() or db.commit(), I get the following error
`java.lang.IllegalArgumentException: can't parse argument number: firstName=#12345`

**Comment by anidotnet** [comment] 2019-04-11 03:51
Using the code provided here, I could not reproduce this issue. Is it possible for you to send me a sample project? You can upload the sample zipped project here directly.

**Comment by Vijeta141** [comment] 2019-04-11 11:01
Hi, so i found out why that document is not being added. Whenever i create a document using the following code I am not facing any issues.


    private Nitrite db;
    //private ObjectRepository<Rules> repository;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);


        if (db == null) {

            String fileName = getFilesDir().getPath() + "/test.db";
            Log.i("Nitrite", "Nitrite file - " + fileName);
            db = Nitrite.builder()
                    .filePath(fileName)
                    .openOrCreate("test-user", "test-password");
           ArrayList<String> s = new ArrayList<String>();
                s.add("orange");
                s.add("banana");
            NitriteCollection collection = db.getCollection("Rules");
            Document doc = Document.createDocument("firstName", "#12345")
                    .put("lastName", "Doe")
                    .put("birthDay", new Date())
                    .put("data", new byte[] {1, 2, 3})
                    .put("fruits", s)
                    .put("note", "a quick brown fox jump over the lazy dog");
            collection.insert(doc);

            Exporter exporter = Exporter.of(db);
            String fileName1 = getFilesDir().getPath() + "/Rules.json";
            exporter.exportTo(fileName1);
        }
    }

**Comment by Vijeta141** [comment] 2019-04-11 11:03
Although if i use 
`.put("fruits", new ArrayList<String>() {{ add("apple"); add("orange"); add("banana"); }})`
the document seems to be overwritten if i run the app again.
In the example_android_project i added this same line in the write method present in User class and i faced the same issue. On adding a user again the past user is no longer present in the repository.

**Comment by anidotnet** [comment] 2019-04-13 14:03
You should not create list like that. What this is actually doing is creating a class derived from `ArrayList<String>` and then declare a static initializer. This is actually an inner class of the containing class, and so it'll have an implicit `this` (this$0) pointer. 

While saving data in nitrite, this `this` pointer is failing with `NotSerializableException`, but somehow mvstore is consuming it silently without coughing up any error message. This unhandled exception is corrupting the database.

I'll raise an issue with h2 database team to get this addressed properly. For the time being try to avoid this static initializer to create a list.

**Comment by anidotnet** [comment] 2019-04-13 16:27
For reference, raised an issue with mvstore team https://github.com/h2database/h2database/issues/1864

**Comment by anidotnet** [comment] 2019-04-23 09:12
Fix has been provided to mvstore repository. It will be available to nitrite after the next release of mvstore.

**Closed by anidotnet** 2019-04-23 09:12 UTC
