### ISSUE TITLE
Joins

### ISSUE THREAD

**Issue by kennywk** [dizitart/nitrite-database#33] opened 2017-11-12 20:29 UTC
Support the ability to join records from other collections providing an output where the selected/join result is the document value.

**Comment by anidotnet** [comment] 2017-11-13 02:54
Could you elaborate more about the feature? It would be better if you provide one example to illustrate it.

**Comment by kennywk** [comment] 2017-11-13 07:30
Sure, for instance in mongo with spring you can use dbref for subdocuments. In spring if you annotate a class with @dbref it will automatically join that document as a property of the annotated document. So for example:

`public class Person{
private String id;
private String name;
private String addressId;
}`

`public class Address{
private String id;
private String street;
}`

Now obviously this is regarding POJOs however if i do a query to select a document by id, It would be awesome if i could join the address document to the returning document where the address document id is equal to the addressId field.

Another example could be that if i have 3 documents that represent portions of an object but in a very normalized way.

`public class Point{
 public String id;
}`

`public class AbsolutePoint extends Point{
public String id;
public Double distance;
}`

`public class GeographicalPoint extends AbsolutePoint{
public String id;
public Double latitude;
public Double longitude;
`

It would be awesome if i could create a aggregated document where i can query the three stores/tables by id and create a single result that includes the fields/attributes from the three source documents where the id matches.

**Comment by anidotnet** [comment] 2017-11-13 07:54
By design I decided not to include aggregation in an embedded database. The detailed reason I described here in issue #24 . If you are asking for something else and I did not understand it, please let me know.

**Comment by kennywk** [comment] 2017-11-13 08:15
Anindya,

Thanks, I can understand the reasoning, however my thoughts regarding my
description of aggregation is not really pertaining to analytics or
calculations, but more so for merging multiple documents into a single
master document (aggregating fields). If you are familiar with JPA or how
other ORMs store records in a relational db, the fields that are also
entities represent a table of its own with a joint table linking the two.
When you query based on the parent entity the ORM will pull the objects
from the tables necessary to make up the parent object. I see this as the
foundation of the request, however it would be nice if i could do it based
on arbitrary documents as sometimes i need to work with relatively dynamic
data.

**Comment by anidotnet** [comment] 2017-11-13 08:36
Does projection serve your purpose? - http://www.dizitart.org/nitrite-database/doc/2.0.0/index.html#projection

**Comment by kennywk** [comment] 2017-11-13 08:42
Projection seems to be based on a single document where you want to only
have certain properties associated with the returned document. What i am
thinking would be projection where a field could be a document returned
from another collection based on a foreign key. For example.

https://drive.google.com/file/d/1XAoVo-B8r0uUTdmBIR6XdHkaEWD7I2Pt/view?usp=sharing

**Comment by anidotnet** [comment] 2017-11-13 08:54
It does look like you are thinking something similar to **lookup** operation in mongo. So if I understand correctly, if you have 2 repositories like ```Address```, ```Person``` 

```java
public class Address {
      private String id;
      private String personId;
      private String streetAddress;
}

public class Person {
    private String id;
    private String name;
}

public class PersonDetails {
    private String id;
    private String name;
    private List<Address> addressList;
}

```
you want to get a result of type ```PersonDetails``` where ```person.id = address.personId```

**Comment by kennywk** [comment] 2017-11-13 09:06
yes, pretty much. Lookup is definitely a better explanation. Ultimately it
is just joining the address and person details into a result of person
details.

**Comment by anidotnet** [comment] 2017-11-13 09:19
Just out of curiosity, what is stopping you to create a repository of ```PersonDetails``` in the first place and get the ```Person``` and ```Address``` objects out of it using projection? Unlike sql databases, here you can persists embedded object directly to the database.

**Comment by kennywk** [comment] 2017-11-13 09:30
Good question, So i'm working on a project where the source data model is
really normalized. And the data is transmitted via database replication.
Each object has its own table and FKs represent the attribute children
objects. There are also levels of inheritance where Object A extends Object
B but instead of just receiving Object B that contains the fields of Object
A, i get the entire inheritance hierarchy. Object B does not contain the
fields of Object A.  So my thoughts were that i could use Nitrite initially
as a staging db for these records, then using the querying, joining and
projection to create the denormalized representation and create a new
denormalized domain model. I cannot control the source and by having a
staging environment such as describe would save me from having to
explicitly mapping each table to a new domain model... or at least reduce
the amount necessary.

**Comment by kennywk** [comment] 2017-11-13 09:52
I think that a lookup would be great and very helpful in my case. I think
that others could use it as well, so it would not be specific to my use
case. I'm attempting to build the source now, will see what else i can come
up with.

Ultimately, the same thing could be achieved manually, however if it could
be automated via the code that would be awesome.

**Comment by anidotnet** [comment] 2017-11-13 12:05
I have come up with a basic design as follows:

```java
Lookup lookup = new Lookup();
lookup.localField = "id";
lookup.foreignField = "personId";
lookup.targetField = "addressList";

Cursor cursor = collection1.find().join(collection2.find(), lookup); // for documents
Cursor<PersonDetails> cursor = repo1.find().join(repo2.find(), lookup); // for objects
```

Let me know your thoughts

**Comment by kennywk** [comment] 2017-11-13 12:18
Looks good to me if the output is as expected.... Perhaps using a builder
pattern may make it flow better

Join join = new
Join.Builder().where("id").eq("otherId").from(collection1.find()).applyTo("addressList");
Cursor cursor = collection1.find().join(join)

Ideally it should work for both collections and single objects/documents.

Thanks for your effort!

**Comment by anidotnet** [comment] 2017-11-13 12:33
I am not inclined to introducing builder patterns right now, as other constructs like query, projection does not have any corresponding builders yet. May be later when I introduce builders for other constructs, I'll definitely add one for it. But for the first step I want to keep it as simple as possible.

**Comment by kennywk** [comment] 2017-11-13 12:35
Understand completely. Thanks for your efforts!

**Comment by anidotnet** [comment] 2017-11-14 06:50
I have made a commit on master. Please build it locally and test. Let me know if it serves your purpose. Once confirmed, I'll do a release, then you will be able to refer it from maven central.

**Comment by kennywk** [comment] 2017-11-14 07:49
Anindya,

Thanks, i will do that as soon as possible.

**Comment by anidotnet** [comment] 2017-11-16 05:45
Let me know the outcome so I can close this issue.

**Comment by kennywk** [comment] 2017-11-16 07:27
I’ve tested the issue. It works as expected. Thanks!

**Comment by anidotnet** [comment] 2017-11-16 08:00
Thanks for confirmation. Closing this issue.

**Closed by anidotnet** 2017-11-16 08:00 UTC
Labels: enhancement
