### ISSUE TITLE
Potassium Nitrite 3.2.0 - NoSuchMethodError: com.fasterxml.jackson.module.kotlin.KotlinModule.<init>(IILkotlin/jvm/internal/DefaultConstructorMarker;)V

### ISSUE THREAD

**Issue by MadamFoxyCoxy** [dizitart/nitrite-database#164] opened 2019-05-10 01:47 UTC
**Code:**
```kotlin
fun main() {
    nitrite {
        path = "test.db"
        autoCommitBufferSize = 2048
        compress = true
    }
}
```
**Error Stack:**
```
Exception in thread "main" java.lang.NoSuchMethodError: com.fasterxml.jackson.module.kotlin.KotlinModule.<init>(IILkotlin/jvm/internal/DefaultConstructorMarker;)V
	at org.dizitart.kno2.KNO2JacksonFacade.createObjectMapper(KNO2JacksonFacade.kt:40)
	at org.dizitart.no2.mapper.JacksonFacade.createObjectMapper(JacksonFacade.java:95)
	at org.dizitart.no2.mapper.JacksonFacade.<init>(JacksonFacade.java:63)
	at org.dizitart.kno2.KNO2JacksonFacade.<init>(KNO2JacksonFacade.kt:36)
	at org.dizitart.kno2.KNO2JacksonFacade.<init>(KNO2JacksonFacade.kt:36)
	at org.dizitart.kno2.KNO2JacksonMapper.<init>(KNO2JacksonMapper.kt:33)
	at org.dizitart.kno2.Builder.createNitriteBuilder$potassium_nitrite(Builder.kt:132)
	at org.dizitart.kno2.BuilderKt.nitrite(Builder.kt:166)
	at org.dizitart.kno2.BuilderKt.nitrite$default(Builder.kt:163)
	at MainKt.main(Main.kt:2)
	at MainKt.main(Main.kt)
```
**Java Version:**
```
openjdk 11.0.2 2019-01-15
OpenJDK Runtime Environment (build 11.0.2+9-Ubuntu-3ubuntu118.04.3)
OpenJDK 64-Bit Server VM (build 11.0.2+9-Ubuntu-3ubuntu118.04.3, mixed mode, sharing)
```
**Kotlin Version:** 1.3.21
**OS:**
```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
```

Let me know if you need anything else. Thanks for having a look at this issue <3

**Comment by anidotnet** [comment] 2019-05-10 04:46
I can't reproduce your issue. Here is my gradle script

```gradle
plugins {
    id 'org.jetbrains.kotlin.jvm' version '1.3.21'
}

group 'org.dizitart.kno2.test'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
    implementation "org.dizitart:potassium-nitrite:3.2.0"
}

compileKotlin {
    kotlinOptions.jvmTarget = "1.8"
}
compileTestKotlin {
    kotlinOptions.jvmTarget = "1.8"
}
```

and here is my kotlin file

```kotlin
package org.dizitart.kno2.test

import org.dizitart.kno2.nitrite

fun main() {
    val db = nitrite {
        path = "test.db"
        autoCommitBufferSize = 2048
        compress = true
    }

    println(db.context.filePath)

}
```

with

```
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
```

and 

```
Distributor ID: Ubuntu
Description:    Ubuntu 19.04
Release:        19.04
Codename:       disco
```

If you are still seeing the issue, would you care to send me some reproducible code?

**Comment by anidotnet** [comment] 2019-05-10 04:52
Could you also tell me what version of `jackson-module-kotlin` your project is resolving to? May be you are using a different version of the library than required. You need to be on 2.9.5.

**Comment by MadamFoxyCoxy** [comment] 2019-05-10 06:22
You're code does work fine on my end, and looking into my libraries, the version for `jackson-module-kotlin` is `2.9.8`

I'm going to go through my libraries and see which one added the new one. Thanks

**Comment by MadamFoxyCoxy** [comment] 2019-05-10 06:24
Oh right, here is my `build.gradle` and the code above triggered the error for me:
```groovy
import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    kotlin("jvm") version "1.3.31"
    id("com.github.johnrengelman.shadow") version "2.0.4"
    application
}

repositories {
    maven { url = uri("https://jitpack.io") }
    mavenCentral()
    jcenter()
}

dependencies {
    // JetBrains Kotlin Dependencies
    implementation(kotlin("stdlib-jdk8"))
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.1.1")
    // Handy Libraries
    implementation("com.google.guava:guava:27.1-jre")
    // Reflection Extension
    implementation("org.reflections:reflections:0.9.11")
    // Logger Handler
    implementation("ch.qos.logback:logback-classic:1.2.3")
    // JSON Handler
    implementation("com.beust:klaxon:5.0.1")
    // Database Libraries
    implementation("org.litote.kmongo:kmongo:3.9.2")
    implementation("org.dizitart:potassium-nitrite:3.2.0")
    // Encryption Handler
    implementation("com.github.rockaport:alice:0.9.0")
    // Discord API Wrapper
    implementation("net.dv8tion:JDA:3.8.3_463")
}

tasks.withType<KotlinCompile> {
    kotlinOptions.jvmTarget = "1.8"
    kotlinOptions.freeCompilerArgs = listOf("-Xexperimental=kotlin.ExperimentalUnsignedTypes")
}

application {
    mainClassName = "MainKt"
}

tasks {
    "shadowJar"(ShadowJar::class) {
        classifier = ""
        destinationDir = file("build")
    }
}```

**Comment by anidotnet** [comment] 2019-05-12 10:39
It looks like there is an issue with transitive dependencies. Your one of the dependencies - `org.litote.kmongo:kmongo:3.9.2` has introduced `jackson-module-kotlin` of version 2.9.8. In this version the signature of the constructor of  `KotlinModule` has changed. That's why this error.

The solution is to exclude the dependency from kmongo and use the one provided by kno2.

```kotlin
implementation("org.litote.kmongo:kmongo:3.9.2") {
   exclude("com.fasterxml.jackson.module", "jackson-module-kotlin")
}
```

**Closed by anidotnet** 2019-05-12 10:39 UTC
