### ISSUE TITLE
Debugger not working on Nitrite code on Windows 10

### ISSUE THREAD

**Issue by swissfreedev** [dizitart/nitrite-database#61] opened 2018-03-14 11:51 UTC
I use Netbeans 8.2 as IDE, one of my javafx solution can't be debugged due to an error

**"Klassenunterbrechung für org.dizitart.no2.NitriteCollection aufgetreten."**

Debugging can be started and is suddently interruptes  "class broken in CollectionFactory.java:43 ???

Any idea? Is this an known issue ? I still use Nitrite 2.1.0

```
User program running
LineBreakpoint MainApp.java : 68 erfolgreich übermittelt.
LineBreakpoint MainApp.java : 20 erfolgreich übermittelt.
Haltepunkt erreicht in 68 von Klasse ui.MainApp in Thread main.
Thread main stopped at MainApp.java:68.
User program running
Haltepunkt erreicht in 20 von Klasse ui.MainApp in Thread JavaFX Application Thread.
Thread JavaFX Application Thread stopped at MainApp.java:20.
User program running
MethodBreakpoint [org.dizitart.no2.NitriteCollection].update '(Lorg/dizitart/no2/Filter;Lorg/dizitart/no2/Document;)Lorg/dizitart/no2/WriteResult;' erfolgreich übermittelt.
MethodBreakpoint [org.dizitart.no2.NitriteCollection].insert '(Lorg/dizitart/no2/Document;[Lorg/dizitart/no2/Document;)Lorg/dizitart/no2/WriteResult;' erfolgreich übermittelt.
**Klassenunterbrechung für org.dizitart.no2.NitriteCollection aufgetreten.**
Thread JavaFX Application Thread stopped at CollectionFactory.java:43
```.

**Comment by swissfreedev** [comment] 2018-03-14 12:17
additional info the error happens here:


```
    public static ObjectRepository<Region> repRegion;
    public static Nitrite dbMain;

    public void InitDB() {
        LoadPreferences();
        File file = new File(dbPath);
        if (file.exists()) {
            Close(); //trennen falls verbunden
            preferences = Preferences.userRoot().node(this.getClass().getName());
            dbPath = preferences.get("dbpath", ""); //+default wert
            dbMain = Nitrite.builder().compressed().filePath(dbPath).openOrCreate();
       
            repRegion = dbMain.getRepository(Region.class);  //>> debugger klassenunterbrechung
```

		...

**Comment by anidotnet** [comment] 2018-03-14 13:48
Could you please translate this error into english? Could not understand the error message in the log? Can you try debugging it in other IDE say eclipse or IntelliJ. I personally work in IntelliJ but I never came across this issue while debugging a JavaFX application.

Moreover, try to use the recent snapshot - 2.2.0-SNAPSHOT

**Comment by swissfreedev** [comment] 2018-03-14 14:57
Interesting. Literally translated it just means "class interruption occured in NitriteCollection...". You don't find any information about this error in the internet at a first glance. As I wrote in my second post the debugging process seem to by disturbed in the line repRegion = dbMain.getRepository(Region.class); 
where the repositories are filled. The repositories are declared public static in order to be use in the whole application, could that be the reason?: By the way I updates to nitrite 2.1.1. same behavior.. I could test it  with the latest snapshot as well, or I use local instances of repositories instead of statics, maybe it helps.

**Comment by anidotnet** [comment] 2018-03-14 16:22
Declaring it as static might not be the problem, but you can rule it out by testing it as an instance variable. 

Is it possible for you to change the IDE and try? I am suspecting it might be the Netbeans debugger that is causing it.

**Comment by swissfreedev** [comment] 2018-03-14 16:41
Ok, good idea.
Just now I did reproduce the same error in my unit test

```
        db = Nitrite.builder().compressed().filePath(GetDBFullPath()).openOrCreate(); //ohne gummi
        NitriteCollection collection1 = db.getCollection("typ"); >error
```

**Comment by anidotnet** [comment] 2018-03-14 18:28
I just downloaded Netbeans 8.2 in my ubuntu 17.10 and ran with jdk1.8.0_77 (64-bit) a sample maven project with debugging on

![image](https://user-images.githubusercontent.com/696662/37423279-7325c39a-27e3-11e8-98aa-caf3fc3d4dfe.png)

I did not find this issue there. Debugger successfully stepped over the statement causing issue for you.

**Comment by swissfreedev** [comment] 2018-03-15 11:40
Hi Anindya,
I executed some tests yesterday evening: Funny results for all Microsoft lovers ;-) 
It is not a javafx, nor Nitrite, Netbeans, Java issue... 
The debugging process is only interrupted on a Windows 10 PC running NB + the application
At home I use SUSE Leap 43.2 it works fine, in my office Win10, then any calls like db.getCollection(), rep.find() etc. stops the debugging process: the workaround, don't use Win10...
Best regards. Thanks for your support. Pascal

**Comment by anidotnet** [comment] 2018-03-15 15:01
Good find. I'll try to fire up my win10 installation and see why it is happening. If there is any issue at nitrite's side I'll try to provide a fix

**Comment by anidotnet** [comment] 2018-03-17 05:09
I tried it under my Win 10, but again I could not reproduce this issue. I am using jdk1.8.0_131 (64-bit).

![image](https://user-images.githubusercontent.com/696662/37551842-bce27824-29ce-11e8-97b8-25572a8a7046.png)

You can try once by upgrading the Netbeans debugger. Now I am closing this issue as not reproducible. Feel free to open it again if you find anything reproducible.

**Closed by anidotnet** 2018-03-17 05:09 UTC
Labels: not-reproducible
