### ISSUE TITLE
Nitrite DateGate not syncing

### ISSUE THREAD

**Issue by dustin-auby** [dizitart/nitrite-database#91] opened 2018-07-31 12:37 UTC
Hi all, i am trying to set up DataGate to handle replication across devices. The DataGate starts up successfully and the client connects to it but no replication happens. can anyone assist

**Comment by anidotnet** [comment] 2018-07-31 14:57
Can you please post your replication setup code and datagate docker file here?

**Comment by dustin-auby** [comment] 2018-07-31 20:06
Hi I have used the code strait out of the examples. I have used a custom mongodb installation and not docker. please see the code bellow. i have used the same code in both the client and server

`
        File db_home = new File("database");
        if(!db_home.exists()){
            db_home.mkdir();
        }
         db = Nitrite.builder()
                .compressed()
                .filePath("database/test.db")
                .openOrCreate(username, password);


// connect to a DataGate server running at localhost 9090 port
        DataGateClient dataGateClient = new DataGateClient("http://localhost:9090")
                .withAuth(username, password);
        DataGateSyncTemplate syncTemplate
                = new DataGateSyncTemplate(dataGateClient, "remote-collection@core");
//        NitriteCollection collection = db.getCollection(collection_name);
        ObjectRepository<Employee> employeeStore = db.getRepository(Employee.class);
// create sync handle
        SyncHandle syncHandle = Replicator.of(db)
                .forLocal(employeeStore)
                // a DataGate sync template implementation
                .withSyncTemplate(syncTemplate)
                // replication attempt delay of 1 sec
                .delay(timeSpan(1, TimeUnit.SECONDS))
                // both-way replication
                .ofType(ReplicationType.BOTH_WAY)
                // sync event listener
                .withListener(new SyncEventListener() {
                    @Override
                    public void onSyncEvent(SyncEventData eventInfo) {
                        System.out.println("Synced");
                    }
                })
                .configure();

        // start sync in the background using handle
        syncHandle.startSync();`

**Comment by anidotnet** [comment] 2018-08-01 04:24
Have you created the client auth credential and user credentials prior to this? If not check this [link](https://www.dizitart.org/nitrite-database/#security-2)

And also create an admin account in your mongodb if you want to use DataGate portal

```javascript
db.getCollection('no2.datagate.users').insert({
    userName: "admin",
    password: "password",
    accountNonExpired: true,
    accountNonLocked: true,
    credentialsNonExpired: true,
    enabled: true,
    authorities: ["ADMIN"]
});
```

You can have a look at this integration test file - [SyncIntegrationTest](https://github.com/dizitart/nitrite-database/blob/master/nitrite-datagate/src/test/java/org/dizitart/no2/datagate/SyncIntegrationTest.java) to see how it works.

**Comment by dustin-auby** [comment] 2018-08-01 08:13
Hi I have added the user and am able to login tho the management portal but it shows no users and no clients or documents
![n_dashboard](https://user-images.githubusercontent.com/38311779/43509624-73972604-9573-11e8-8e89-2717450b1092.PNG)
![n_nousers](https://user-images.githubusercontent.com/38311779/43509627-7614bbf8-9573-11e8-9c38-f6feced83a0b.PNG)

**Comment by anidotnet** [comment] 2018-08-01 10:44
I have already mentioned in the comment above. You need to create a client account through this portal. This client credential is required to connect to DataGate server from the app.

From the app, you need to create another set of credentials for each user of the app. This credential is required to segregate data for each user of your app. Please look into the integration test file I have linked in the previous comment. This should give you an idea on how you have to do the initial setup for your app.

Look into the `setUp()` method of `SyncIntegrationTest` and notice 2 methods `prepareClientAuth()` and `prepareUserAuth()` in it. These are one time methods to set up the required client/user credentials. Once users are set up properly, look into `testDocumentSync()` on how to setup replication code.

After doing all these if you still could not see any replication being happened, look into the DataGate log to get an idea about the root cause.

**Comment by anidotnet** [comment] 2018-08-03 07:08
Is this resolved for you? Let me know so that I can close this.

**Comment by dustin-auby** [comment] 2018-08-03 07:36
Hi, no i haven't fixed it yet i added the user with the code you sent above `db.getCollection('no2.datagate.users').insert({
    userName: "admin",
    password: "password",
    accountNonExpired: true,
    accountNonLocked: true,
    credentialsNonExpired: true,
    enabled: true,
    authorities: ["ADMIN"]
});`

This code executed successfully but the management portal does not see the user i have added. and as far as i can see the management portal does not have the ability to add users within the interface. am i missing something.

**Comment by anidotnet** [comment] 2018-08-03 08:10
What you have created is a admin user with ADMIN role, it is used only to login and manage the portal. You will not see admin user in the portal's user section. 

As I mentioned, you need to create a client user with CLIENT role next. If you have looked into the integration test code I mentioned earlier, you would see that you need to create the user in mongodb using the code below

```javascript
db.getCollection('no2.datagate.users').insert({
    userName: "client",
    password: "password",
    accountNonExpired: true,
    accountNonLocked: true,
    credentialsNonExpired: true,
    enabled: true,
    authorities: ["CLIENT"]
});

```
This client credential will be required by your app to make call to DataGate api.

After that you need to create sync user with USER role. You have to create this user from your app to sync collections.

```java
String remoteCollection = "test-collection@user123";

UserAccount userAccount = new UserAccount();
userAccount.setUserName("user123");
userAccount.setPassword("password");
userAccount.setAuthorities(new String[]{ "USER" });
userAccount.setCollections(new ArrayList<String>() {{
      add(remoteCollection);
}});

DataGateClient dataGateApiClient = new DataGateClient("http://localhost:9090")
       .withAuth("client", "password");

DataGateUserTemplate userTemplate = new DataGateUserTemplate(dataGateApiClient);
// create the sync user here
userTemplate.createRemoteUser(userAccount);

```

Once a sync user (user123) is created in the system, you can use this user credential to sync nitrite database

```java
// create a user agent so that the device type will show up in portal
UserAgent userAgent = new UserAgent();
userAgent.setAppName("MyAwesomeApp");
userAgent.setAppVersion("1.4.2");
userAgent.setDevice("Android");
userAgent.setClientId("cl154");

DataGateClient dataGateSyncClient = new DataGateClient("http://localhost:9090")
         .withAuth("user123", "password")
         .withUserAgent(userAgent);

DataGateSyncTemplate syncTemplate = new DataGateSyncTemplate(dataGateSyncClient, 
          remoteCollection);

SyncHandle syncHandle = Replicator.of(db)
        // start replication of your local collection named - myLocalCollection
        .forLocal(myLocalCollection)
        .withSyncTemplate(syncTemplate)
        // replication attempt delay of 1 sec
        .delay(timeSpan(1, TimeUnit.SECONDS))
        // both-way replication
        .ofType(ReplicationType.BOTH_WAY)
        // sync event listener
        .withListener(new SyncEventListener() {
            @Override
            public void onSyncEvent(SyncEventData eventInfo) {

            }
        })
        .configure();

// start sync in the background using handle
syncHandle.startSync();
```

After this setup, you will be able to see **client** and **user123** in the portal. And when sync will happen, you will see the device details also in the portal.

**Comment by dustin-auby** [comment] 2018-08-03 13:41
Ok i have literally copied your example down to the dot. i now see both users in the portal the client and the user but still the data will not sync i have added 100 rows of test data and it shows 0 Collections and 0 Documents in the management portal

**Comment by anidotnet** [comment] 2018-08-03 17:10
Would you please upload 2 log files - your apps debug log and DataGate debug log? Before capturing the DataGate log, change the log level to debug in your `datagate.properties` file

```properties
logging.level.org.dizitart.no2=INFO -> change it to DEBUG
```

**Comment by dustin-auby** [comment] 2018-08-06 06:16
Hi, I managed to get them syncing initially but once i started to do bigger tests they fell out of sync. i did a test adding 10000 records and one is stuck on 4600 out of 10000. even if i restart the clients they remain out of sync

**Comment by anidotnet** [comment] 2018-08-06 06:27
@dustin-auby you need to increase the timeout settings if you are trying to sync large data set. Look into this issue - https://github.com/dizitart/nitrite-database/issues/73 for reference.

**Comment by dustin-auby** [comment] 2018-08-06 06:59
Ok what should i be setting it too i have tried 1000, 5000 and 100000 with no success

**Comment by dustin-auby** [comment] 2018-08-06 07:00
Will i have to delete the mongo database and start again as since it has gone out of sync i cant even sync a single addition i have to delete the local database and start again in order to update the data

**Comment by anidotnet** [comment] 2018-08-06 07:01
You need to reset the remote collection in mongo and start re-sync from the beginning with higher `readTimeout` and `connectTimeout` value. Remember these values are in milliseconds. You need to calculate the time you need depending on your document size. Try to estimate the time taken for each document to sync from your log and multiply it by number of documents.

**Comment by dustin-auby** [comment] 2018-08-06 08:27
Ok but the system is dynamic so there is no way i can know how many rows are going to be inserted can i just set it to like 10000 for worst case scenario will that effect the system.

**Comment by dustin-auby** [comment] 2018-08-06 08:35
Hi Sorry this cant be the issue i have it set to 20000 and i cant even sync 5000 tiny records

**Comment by anidotnet** [comment] 2018-08-06 08:37
How much time it is taking per document for you? Can you figure that out from the log?

**Comment by anidotnet** [comment] 2018-08-06 08:45
Would you also upload your datagate debug log and app debug log here? And also remember, replication logic is optimized for incremental sync not bulk sync. So bulk sync takes long time. For 5000 tiny doc I'll suggest you need something much more than 20 sec as timeout. Datagate syncs over http traffic and it has its overhead.

**Comment by dustin-auby** [comment] 2018-08-06 08:59
[datagate.log](https://github.com/dizitart/nitrite-database/files/2261844/datagate.log)

Ok will try a longer timeout

**Comment by dustin-auby** [comment] 2018-08-06 09:46
ok set the timeout to 200000 still cant sync 5000 records it does sync 1000 in under 2 seconds though . once i try 5000 it gets stuck and will not sync anymore weather i add 1 or 1000. i have tried restarting the server
[datagate.zip](https://github.com/dizitart/nitrite-database/files/2262011/datagate.zip)

**Comment by anidotnet** [comment] 2018-08-06 10:31
Could you please also upload nitrite debug log from your application?

**Comment by dustin-auby** [comment] 2018-08-06 11:11
Ok i have enabled the logs, do they go to the same file or are they somewhere else
[datagate.zip](https://github.com/dizitart/nitrite-database/files/2262264/datagate.zip)

**Comment by anidotnet** [comment] 2018-08-06 11:40
It's a separate log file. Configure logging framework in your app and capture the debug log.

**Comment by dustin-auby** [comment] 2018-08-06 13:15
[Datagate output.zip](https://github.com/dizitart/nitrite-database/files/2262653/Datagate.output.zip)
[datagate.log.zip](https://github.com/dizitart/nitrite-database/files/2262654/datagate.log.zip)
[App DEBUG OUTPUTlogs_1_06-08-2018-03-11-51.zip](https://github.com/dizitart/nitrite-database/files/2262656/App.DEBUG.OUTPUTlogs_1_06-08-2018-03-11-51.zip)

**Comment by anidotnet** [comment] 2018-08-06 19:05
These logs are overwhelming and making it difficult for me to pinpoint the issue. 

And your app debug logs contains nothing. Setup a slf4j compatible logging framework for your app and set the log level to DEBUG before capturing it. It should contain verbose nitrite database log.

Do one thing to capture the relevant log. Set the delay to 1 min in `SyncTemplate` as follows:

```java
SyncHandle syncHandle = Replicator.of(db)
        // start replication of your local collection named - myLocalCollection
        .forLocal(myLocalCollection)
        .withSyncTemplate(syncTemplate)
        // replication attempt delay of 1 min
        .delay(timeSpan(1, TimeUnit.MINUTES ))
        // both-way replication
        .ofType(ReplicationType.BOTH_WAY)
        // sync event listener
        .withListener(new SyncEventListener() {
            @Override
            public void onSyncEvent(SyncEventData eventInfo) {

            }
        })
        .configure();
```
Capture the log for 5 min, so it will contains 5 run only.

**Comment by dustin-auby** [comment] 2018-08-07 08:18
Hi i have decided to use an alternative sync method. thanks for all the help but i need my application to recover and keep up to date regardless of how many objects are needed and how long the system has been behind. this method seems to unstable for what i am looking for.

**Closed** 2018-08-07 11:28 UTC
