### ISSUE TITLE
Nitrite Failing on Second Write to DB

### ISSUE THREAD

**Issue by lonpalmer** [dizitart/nitrite-database#31] opened 2017-10-29 14:51 UTC
First write into a table is successful but second write is throwing an exception.  I'm not closing the database explicitly:

```
val DB_PATH: String = "iotdb.database";
val database : Nitrite by lazy {makeOrOpenDb()};

private fun makeOrOpenDb(): Nitrite
{
    val db = Nitrite.builder().compressed().filePath(DB_PATH).openOrCreate();
    return db;
}

fun saveReport(report: IIotReport)
{
    database.getCollection(DbTable.Reports.tblName).insert(makeDocument(report));
}

private fun makeDocument(report: IIotReport): Document
{
    val doc = Document();
    doc.put(DB_COL_TYPE, report.type.toString());
    doc.put(DB_COL_DATE, report.date.time);
    doc.put(DB_COL_SN, report.serialNumber.toString());
    doc.put(DB_COL_REC, report);
    return doc;
}
```

Error: 
```

Hello 2
Report Server Running
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Received RangerReport(date=Sun Oct 29 14:43:36 UTC 2017, serialNumber=5342313135371314340C, range=300, digitalIo=-1, atodOne=-1, atodTwo=-1)
Received RangerReport(date=Sun Oct 29 14:43:47 UTC 2017, serialNumber=5342313135371314340C, range=300, digitalIo=-1, atodOne=-1, atodTwo=-1)
Exception in thread "Report Server" java.lang.IllegalStateException: This store is closed [1.4.196/4]
        at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:765)
        at org.h2.mvstore.MVStore.checkOpen(MVStore.java:2409)
        at org.h2.mvstore.MVStore.openMap(MVStore.java:443)
        at org.h2.mvstore.MVStore.openMap(MVStore.java:427)
        at org.dizitart.no2.store.NitriteMVStore.openMap(NitriteMVStore.java:87)
        at org.dizitart.no2.Nitrite.getCollection(Nitrite.java:116)
        at db.MainDbKt.saveReport(MainDb.kt:167)
        at iotsvr.ReportSvrKt$startReportServer$reportSvr$1.invoke(ReportSvr.kt:93)
        at iotsvr.ReportSvrKt$startReportServer$reportSvr$1.invoke(ReportSvr.kt)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Caused by: java.lang.IllegalStateException: Last block not stored, possibly due to out-of-memory [1.4.196/3]
        at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:765)
        at org.h2.mvstore.MVStore.storeNowTry(MVStore.java:1094)
        at org.h2.mvstore.MVStore.storeNow(MVStore.java:1050)
        at org.h2.mvstore.MVStore.commitAndSave(MVStore.java:1039)
        at org.h2.mvstore.MVStore.writeInBackground(MVStore.java:2489)
        at org.h2.mvstore.MVStore$BackgroundWriterThread.run(MVStore.java:2720)

```

**Comment by lonpalmer** [comment] 2017-10-29 15:50
Just a note, I reported this issue earlier but it was closed as un able to reproduce.  I'm reproducing it 100% now.

**Comment by anidotnet** [comment] 2017-10-29 15:52
Based on your description I have created below example:

```kotlin
fun main(args: Array<String>) {    
    for (i in 0..5) {
        saveReport(IIotReport())
    }
}

val DB_PATH: String = "iotdb.database"
val database : Nitrite by lazy { makeOrOpenDb() }

private fun makeOrOpenDb(): Nitrite {
    val db = Nitrite.builder().compressed().filePath(DB_PATH).openOrCreate()
    return db
}

fun saveReport(report: IIotReport) {
    database.getCollection("report").insert(makeDocument(report))
}

private fun makeDocument(report: IIotReport): Document {
    val doc = Document()
    doc.put("type", report.type.toString())
    doc.put("date", report.date.time)
    doc.put("sn", report.serialNumber.toString())
    doc.put("rec", report)
    return doc
}

val counter = AtomicInteger(1)

class IIotReport {
    var type: String = "test report ${counter.getAndIncrement()}"
    var date: Date = Date()
    var serialNumber: Long = System.currentTimeMillis()
}
```

but I am still unable to reproduce. It is writing data properly for me. Can you please work on the code I provided here and make it reproducible? If you can share your code privately that is also okay with me. Somehow, I need to reproduce it.

**Comment by lonpalmer** [comment] 2017-10-29 18:40
This works fine on my windows 10 development work station.  It fails, however on the linux production environment machine.  

I could send the created database to you if that would help you understand what's going on.

**Comment by anidotnet** [comment] 2017-10-29 18:50
My own machine is also Ubuntu 17.10, 64bit. The problem is not with database file I think. Can you create a heap dump and check what is going on? According to the error message there might be an OOM happening.  Heap dump might help you to debug it.

**Comment by lonpalmer** [comment] 2017-10-29 19:44
Memory use for the java process is very, very low.  I can’t imagine it’s OOM.

I’ll get you a heap dump ASAP.  NOTE this did happen on my Windows machine in the past and the way I got cleared the problem was to delete the database and recreate it.

________________________________

**Comment by lonpalmer** [comment] 2017-10-31 02:27
I looked at the Heap Dump and it was very small.  3.5MB for the entire application.  Nothing seemed out of the ordinary.  I'm happy to send it to you if you wouldn't mind looking at it.

I have some more information for you:

1) If I write to the database quickly (2 inserts in a couple of seconds) both inserts are successful.  Then when the third insert takes more time (approx. 10s) it fails.  It's like some process in Nitrite is closing the DB.  Perhaps the process that writes memory cached data to the file.

**Comment by anidotnet** [comment] 2017-10-31 04:35
With your last description (delay of 10 sec.) I was able to reproduce the issue. The culprit  is this line:

```kotlin
doc.put(DB_COL_REC, report)
```
The reason is, you are storing a java/kotlin object inside a document. Java mandates, you mark any object with```Serializable``` if you want to binary serialize it, or you implement ```readObject()``` and ```writeObject()```. If you don't, the object won't be serialized and a ```NotSerializableException``` will be thrown. Your report object does not implement ```Serializable``` and that's why it is throwing an exception while storing it, but MVStore library is somehow eating the exception and not bubbling it up the stack. This exception is panicking and closing the MVStore prematurely. That's why in the next write you see this exception as "store is closed".

The reason you are not able to see this error while writing in close succession is, MVStore writes data in a background thread after certain interval. By the time the write loop completes, MVStore does not writes data to disk, so you are not seeing this error. But if you introduce delay in writes, the MVStore background thread kicks in and try to writes data whatever is in the buffer. When it fails, it panics and closes the store and failing the next write.

So the remedy is - either implement ```Serializable``` for your report class, or convert your report class to a ```Document``` of primitive types, or use ```ObjectRepository<IIotReport>``` instead of ```NitriteCollection```. ObjectRepository will convert your report class into a Document and takes care of the serialization.

Meantime, as MVStore is eating up the exception, I'll put a check of ```Serializable``` object in the code, so that user get's a proper error message.

**Comment by lonpalmer** [comment] 2017-10-31 16:34
Thank you, Anindya.  That makes perfect sense.


I'll move to an ObjectRepository.


Regards and thanks for the help!

Lon Palmer

________________________________

**Closed** 2017-11-01 14:50 UTC
Labels: bug
